name: Build

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Run the build command in Docker
    - name: Docker run idf.py build
      run: docker run --rm -v $GITHUB_WORKSPACE:/project -w /project -e HOME=/tmp jjsprandel/scan:v1.0 idf.py build
