name: Docker Build

on:
  push:
    paths:
      - "Dockerfile" # Trigger the workflow only when the Dockerfile is edited
  pull_request:
    paths:
      - "Dockerfile" # Optional: Run on pull requests with Dockerfile edits

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t scan_github_image .
